import { FileText, BookOpen, ClipboardList, BarChart2 } from "lucide-react";

export const resources = [
  {
    slug: "cms-enrollment-moratoria",
    type: "Guide",
    icon: FileText,
    tagColor: "text-cyan-400 bg-cyan-500/10 border-cyan-500/20",
    title: "CMS Provider Enrollment Moratoria",
    subtitle: "What It Is, Why It Matters, and What Agencies Need to Know",
    description: "CMS enrollment moratoria affect which home health agencies can enroll in Medicare in specific regions. This guide explains how moratoria work, why they exist, which agencies are affected, and what steps to take to stay compliant and prepared.",
    topics: [
      "What CMS enrollment moratoria are and why they exist",
      "How moratoria impact new enrollments and ownership changes",
      "Steps agencies should take to verify eligibility",
      "How to monitor CMS updates and stay ahead of changes",
    ],
    pdfPath: "/pdfs/cms-enrollment-moratoria.pdf",
    pageRoute: "/resources/cms-enrollment-moratoria",
    buttonText: "Read the Guide",
  },
  {
    slug: "why-professional-website-matters",
    type: "Playbook",
    icon: BookOpen,
    tagColor: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
    title: "Why a Professional Website Matters",
    subtitle: "More Than Ever for Home Health Agencies",
    description: "In today's environment — with stricter CMS scrutiny, growing competition, and higher expectations from referral sources — a professional website is one of the most important assets your agency can invest in. This playbook explains why, and what a strong site actually does for your business.",
    topics: [
      "How the 2026 Medicare moratorium raises the stakes for credibility",
      "Why referral partners research agencies online before referring",
      "How a website supports compliance readiness and professional perception",
      "The connection between digital presence and sustainable growth",
    ],
    pdfPath: "/pdfs/why-professional-website-matters.pdf",
    pageRoute: "/resources/why-professional-website-matters",
    buttonText: "Read the Playbook",
  },
  {
    slug: "digital-presence-checklist",
    type: "Checklist",
    icon: ClipboardList,
    tagColor: "text-teal-400 bg-teal-500/10 border-teal-500/20",
    title: "Home Health Agency Digital Presence Checklist",
    subtitle: "Every Component Your Agency Should Have in Place",
    description: "Before a patient contacts you, a hospital sends a referral, or a family member requests information, they will likely search for your agency online. This checklist covers every component of a strong digital presence — from your website to your Google Business Profile to your review strategy.",
    topics: [
      "13 digital presence components every home health agency needs",
      "Mobile-friendly design, SEO, and Google Business Profile essentials",
      "Compliance signals, recruitment sections, and professional branding",
      "Reputation management and ongoing website maintenance",
    ],
    pdfPath: "/pdfs/digital-presence-checklist.pdf",
    pageRoute: "/resources/digital-presence-checklist",
    buttonText: "Get the Checklist",
  },
  {
    slug: "marketing-essentials",
    type: "Guide",
    icon: BarChart2,
    tagColor: "text-violet-400 bg-violet-500/10 border-violet-500/20",
    title: "Home Health Agency Marketing Essentials",
    subtitle: "A Practical Guide to Building Awareness and Trust",
    description: "Effective marketing doesn't require a large budget. It requires focus. This practical guide covers the core areas home health agencies should prioritize — from Google Business Profile and local SEO to referral partnerships and content marketing — and explains how each component works together.",
    topics: [
      "Google Business Profile setup and optimization for local visibility",
      "Local SEO strategies that help patients find your agency",
      "Reputation management and review generation best practices",
      "Referral partnerships, content marketing, and website conversion",
    ],
    pdfPath: "/pdfs/marketing-essentials.pdf",
    pageRoute: "/resources/marketing-essentials",
    buttonText: "Read the Guide",
  },
];

export type Resource = typeof resources[number];
