/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnhancementsRouteImport } from './routes/enhancements'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LaunchProgramRouteImport } from './routes/launch-program'
import { Route as MeetOurTeamRouteImport } from './routes/meet-our-team'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as PlaybookClinicalDocumentationQaRouteImport } from './routes/playbook/clinical-documentation-qa'
import { Route as PlaybookHomeHealthAgencyReferralsOnlineRouteImport } from './routes/playbook/home-health-agency-referrals-online'
import { Route as PlaybookHospiceProvidersRouteImport } from './routes/playbook/hospice-providers'
import { Route as PlaybookLongTermCareProvidersRouteImport } from './routes/playbook/long-term-care-providers'
import { Route as PlaybookRevenueCycleBillingRouteImport } from './routes/playbook/revenue-cycle-billing'
import { Route as PlaybookSeniorCareCompaniesRouteImport } from './routes/playbook/senior-care-companies'
import { Route as ResourcesCmsEnrollmentMoratoriaRouteImport } from './routes/resources/cms-enrollment-moratoria'
import { Route as ResourcesDigitalPresenceChecklistRouteImport } from './routes/resources/digital-presence-checklist'
import { Route as ResourcesMarketingEssentialsRouteImport } from './routes/resources/marketing-essentials'
import { Route as ResourcesWhyProfessionalWebsiteMattersRouteImport } from './routes/resources/why-professional-website-matters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnhancementsRoute = EnhancementsRouteImport.update({
  id: '/enhancements',
  path: '/enhancements',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchProgramRoute = LaunchProgramRouteImport.update({
  id: '/launch-program',
  path: '/launch-program',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetOurTeamRoute = MeetOurTeamRouteImport.update({
  id: '/meet-our-team',
  path: '/meet-our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookClinicalDocumentationQaRoute =
  PlaybookClinicalDocumentationQaRouteImport.update({
    id: '/playbook/clinical-documentation-qa',
    path: '/playbook/clinical-documentation-qa',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaybookHomeHealthAgencyReferralsOnlineRoute =
  PlaybookHomeHealthAgencyReferralsOnlineRouteImport.update({
    id: '/playbook/home-health-agency-referrals-online',
    path: '/playbook/home-health-agency-referrals-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaybookHospiceProvidersRoute =
  PlaybookHospiceProvidersRouteImport.update({
    id: '/playbook/hospice-providers',
    path: '/playbook/hospice-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaybookLongTermCareProvidersRoute =
  PlaybookLongTermCareProvidersRouteImport.update({
    id: '/playbook/long-term-care-providers',
    path: '/playbook/long-term-care-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaybookRevenueCycleBillingRoute =
  PlaybookRevenueCycleBillingRouteImport.update({
    id: '/playbook/revenue-cycle-billing',
    path: '/playbook/revenue-cycle-billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaybookSeniorCareCompaniesRoute =
  PlaybookSeniorCareCompaniesRouteImport.update({
    id: '/playbook/senior-care-companies',
    path: '/playbook/senior-care-companies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesCmsEnrollmentMoratoriaRoute =
  ResourcesCmsEnrollmentMoratoriaRouteImport.update({
    id: '/cms-enrollment-moratoria',
    path: '/cms-enrollment-moratoria',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesDigitalPresenceChecklistRoute =
  ResourcesDigitalPresenceChecklistRouteImport.update({
    id: '/digital-presence-checklist',
    path: '/digital-presence-checklist',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesMarketingEssentialsRoute =
  ResourcesMarketingEssentialsRouteImport.update({
    id: '/marketing-essentials',
    path: '/marketing-essentials',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesWhyProfessionalWebsiteMattersRoute =
  ResourcesWhyProfessionalWebsiteMattersRouteImport.update({
    id: '/why-professional-website-matters',
    path: '/why-professional-website-matters',
    getParentRoute: () => ResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/enhancements': typeof EnhancementsRoute
  '/faq': typeof FaqRoute
  '/launch-program': typeof LaunchProgramRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
  '/playbook/clinical-documentation-qa': typeof PlaybookClinicalDocumentationQaRoute
  '/playbook/home-health-agency-referrals-online': typeof PlaybookHomeHealthAgencyReferralsOnlineRoute
  '/playbook/hospice-providers': typeof PlaybookHospiceProvidersRoute
  '/playbook/long-term-care-providers': typeof PlaybookLongTermCareProvidersRoute
  '/playbook/revenue-cycle-billing': typeof PlaybookRevenueCycleBillingRoute
  '/playbook/senior-care-companies': typeof PlaybookSeniorCareCompaniesRoute
  '/resources/cms-enrollment-moratoria': typeof ResourcesCmsEnrollmentMoratoriaRoute
  '/resources/digital-presence-checklist': typeof ResourcesDigitalPresenceChecklistRoute
  '/resources/marketing-essentials': typeof ResourcesMarketingEssentialsRoute
  '/resources/why-professional-website-matters': typeof ResourcesWhyProfessionalWebsiteMattersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/enhancements': typeof EnhancementsRoute
  '/faq': typeof FaqRoute
  '/launch-program': typeof LaunchProgramRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
  '/playbook/clinical-documentation-qa': typeof PlaybookClinicalDocumentationQaRoute
  '/playbook/home-health-agency-referrals-online': typeof PlaybookHomeHealthAgencyReferralsOnlineRoute
  '/playbook/hospice-providers': typeof PlaybookHospiceProvidersRoute
  '/playbook/long-term-care-providers': typeof PlaybookLongTermCareProvidersRoute
  '/playbook/revenue-cycle-billing': typeof PlaybookRevenueCycleBillingRoute
  '/playbook/senior-care-companies': typeof PlaybookSeniorCareCompaniesRoute
  '/resources/cms-enrollment-moratoria': typeof ResourcesCmsEnrollmentMoratoriaRoute
  '/resources/digital-presence-checklist': typeof ResourcesDigitalPresenceChecklistRoute
  '/resources/marketing-essentials': typeof ResourcesMarketingEssentialsRoute
  '/resources/why-professional-website-matters': typeof ResourcesWhyProfessionalWebsiteMattersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/enhancements': typeof EnhancementsRoute
  '/faq': typeof FaqRoute
  '/launch-program': typeof LaunchProgramRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
  '/playbook/clinical-documentation-qa': typeof PlaybookClinicalDocumentationQaRoute
  '/playbook/home-health-agency-referrals-online': typeof PlaybookHomeHealthAgencyReferralsOnlineRoute
  '/playbook/hospice-providers': typeof PlaybookHospiceProvidersRoute
  '/playbook/long-term-care-providers': typeof PlaybookLongTermCareProvidersRoute
  '/playbook/revenue-cycle-billing': typeof PlaybookRevenueCycleBillingRoute
  '/playbook/senior-care-companies': typeof PlaybookSeniorCareCompaniesRoute
  '/resources/cms-enrollment-moratoria': typeof ResourcesCmsEnrollmentMoratoriaRoute
  '/resources/digital-presence-checklist': typeof ResourcesDigitalPresenceChecklistRoute
  '/resources/marketing-essentials': typeof ResourcesMarketingEssentialsRoute
  '/resources/why-professional-website-matters': typeof ResourcesWhyProfessionalWebsiteMattersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/enhancements'
    | '/faq'
    | '/launch-program'
    | '/meet-our-team'
    | '/privacy-policy'
    | '/process'
    | '/resources'
    | '/results'
    | '/services'
    | '/why-us'
    | '/playbook/clinical-documentation-qa'
    | '/playbook/home-health-agency-referrals-online'
    | '/playbook/hospice-providers'
    | '/playbook/long-term-care-providers'
    | '/playbook/revenue-cycle-billing'
    | '/playbook/senior-care-companies'
    | '/resources/cms-enrollment-moratoria'
    | '/resources/digital-presence-checklist'
    | '/resources/marketing-essentials'
    | '/resources/why-professional-website-matters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/enhancements'
    | '/faq'
    | '/launch-program'
    | '/meet-our-team'
    | '/privacy-policy'
    | '/process'
    | '/resources'
    | '/results'
    | '/services'
    | '/why-us'
    | '/playbook/clinical-documentation-qa'
    | '/playbook/home-health-agency-referrals-online'
    | '/playbook/hospice-providers'
    | '/playbook/long-term-care-providers'
    | '/playbook/revenue-cycle-billing'
    | '/playbook/senior-care-companies'
    | '/resources/cms-enrollment-moratoria'
    | '/resources/digital-presence-checklist'
    | '/resources/marketing-essentials'
    | '/resources/why-professional-website-matters'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/enhancements'
    | '/faq'
    | '/launch-program'
    | '/meet-our-team'
    | '/privacy-policy'
    | '/process'
    | '/resources'
    | '/results'
    | '/services'
    | '/why-us'
    | '/playbook/clinical-documentation-qa'
    | '/playbook/home-health-agency-referrals-online'
    | '/playbook/hospice-providers'
    | '/playbook/long-term-care-providers'
    | '/playbook/revenue-cycle-billing'
    | '/playbook/senior-care-companies'
    | '/resources/cms-enrollment-moratoria'
    | '/resources/digital-presence-checklist'
    | '/resources/marketing-essentials'
    | '/resources/why-professional-website-matters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  EnhancementsRoute: typeof EnhancementsRoute
  FaqRoute: typeof FaqRoute
  LaunchProgramRoute: typeof LaunchProgramRoute
  MeetOurTeamRoute: typeof MeetOurTeamRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProcessRoute: typeof ProcessRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  ServicesRoute: typeof ServicesRoute
  WhyUsRoute: typeof WhyUsRoute
  PlaybookClinicalDocumentationQaRoute: typeof PlaybookClinicalDocumentationQaRoute
  PlaybookHomeHealthAgencyReferralsOnlineRoute: typeof PlaybookHomeHealthAgencyReferralsOnlineRoute
  PlaybookHospiceProvidersRoute: typeof PlaybookHospiceProvidersRoute
  PlaybookLongTermCareProvidersRoute: typeof PlaybookLongTermCareProvidersRoute
  PlaybookRevenueCycleBillingRoute: typeof PlaybookRevenueCycleBillingRoute
  PlaybookSeniorCareCompaniesRoute: typeof PlaybookSeniorCareCompaniesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enhancements': {
      id: '/enhancements'
      path: '/enhancements'
      fullPath: '/enhancements'
      preLoaderRoute: typeof EnhancementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-program': {
      id: '/launch-program'
      path: '/launch-program'
      fullPath: '/launch-program'
      preLoaderRoute: typeof LaunchProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-our-team': {
      id: '/meet-our-team'
      path: '/meet-our-team'
      fullPath: '/meet-our-team'
      preLoaderRoute: typeof MeetOurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/clinical-documentation-qa': {
      id: '/playbook/clinical-documentation-qa'
      path: '/playbook/clinical-documentation-qa'
      fullPath: '/playbook/clinical-documentation-qa'
      preLoaderRoute: typeof PlaybookClinicalDocumentationQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/home-health-agency-referrals-online': {
      id: '/playbook/home-health-agency-referrals-online'
      path: '/playbook/home-health-agency-referrals-online'
      fullPath: '/playbook/home-health-agency-referrals-online'
      preLoaderRoute: typeof PlaybookHomeHealthAgencyReferralsOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/hospice-providers': {
      id: '/playbook/hospice-providers'
      path: '/playbook/hospice-providers'
      fullPath: '/playbook/hospice-providers'
      preLoaderRoute: typeof PlaybookHospiceProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/long-term-care-providers': {
      id: '/playbook/long-term-care-providers'
      path: '/playbook/long-term-care-providers'
      fullPath: '/playbook/long-term-care-providers'
      preLoaderRoute: typeof PlaybookLongTermCareProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/revenue-cycle-billing': {
      id: '/playbook/revenue-cycle-billing'
      path: '/playbook/revenue-cycle-billing'
      fullPath: '/playbook/revenue-cycle-billing'
      preLoaderRoute: typeof PlaybookRevenueCycleBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/senior-care-companies': {
      id: '/playbook/senior-care-companies'
      path: '/playbook/senior-care-companies'
      fullPath: '/playbook/senior-care-companies'
      preLoaderRoute: typeof PlaybookSeniorCareCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/cms-enrollment-moratoria': {
      id: '/resources/cms-enrollment-moratoria'
      path: '/cms-enrollment-moratoria'
      fullPath: '/resources/cms-enrollment-moratoria'
      preLoaderRoute: typeof ResourcesCmsEnrollmentMoratoriaRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/digital-presence-checklist': {
      id: '/resources/digital-presence-checklist'
      path: '/digital-presence-checklist'
      fullPath: '/resources/digital-presence-checklist'
      preLoaderRoute: typeof ResourcesDigitalPresenceChecklistRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/marketing-essentials': {
      id: '/resources/marketing-essentials'
      path: '/marketing-essentials'
      fullPath: '/resources/marketing-essentials'
      preLoaderRoute: typeof ResourcesMarketingEssentialsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/why-professional-website-matters': {
      id: '/resources/why-professional-website-matters'
      path: '/why-professional-website-matters'
      fullPath: '/resources/why-professional-website-matters'
      preLoaderRoute: typeof ResourcesWhyProfessionalWebsiteMattersRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesCmsEnrollmentMoratoriaRoute: typeof ResourcesCmsEnrollmentMoratoriaRoute
  ResourcesDigitalPresenceChecklistRoute: typeof ResourcesDigitalPresenceChecklistRoute
  ResourcesMarketingEssentialsRoute: typeof ResourcesMarketingEssentialsRoute
  ResourcesWhyProfessionalWebsiteMattersRoute: typeof ResourcesWhyProfessionalWebsiteMattersRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesCmsEnrollmentMoratoriaRoute: ResourcesCmsEnrollmentMoratoriaRoute,
  ResourcesDigitalPresenceChecklistRoute:
    ResourcesDigitalPresenceChecklistRoute,
  ResourcesMarketingEssentialsRoute: ResourcesMarketingEssentialsRoute,
  ResourcesWhyProfessionalWebsiteMattersRoute:
    ResourcesWhyProfessionalWebsiteMattersRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  EnhancementsRoute: EnhancementsRoute,
  FaqRoute: FaqRoute,
  LaunchProgramRoute: LaunchProgramRoute,
  MeetOurTeamRoute: MeetOurTeamRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProcessRoute: ProcessRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ResultsRoute: ResultsRoute,
  ServicesRoute: ServicesRoute,
  WhyUsRoute: WhyUsRoute,
  PlaybookClinicalDocumentationQaRoute: PlaybookClinicalDocumentationQaRoute,
  PlaybookHomeHealthAgencyReferralsOnlineRoute:
    PlaybookHomeHealthAgencyReferralsOnlineRoute,
  PlaybookHospiceProvidersRoute: PlaybookHospiceProvidersRoute,
  PlaybookLongTermCareProvidersRoute: PlaybookLongTermCareProvidersRoute,
  PlaybookRevenueCycleBillingRoute: PlaybookRevenueCycleBillingRoute,
  PlaybookSeniorCareCompaniesRoute: PlaybookSeniorCareCompaniesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
