/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResourcesCmsEnrollmentMoratoriaImport } from './routes/resources/cms-enrollment-moratoria'
import { Route as ResourcesWhyProfessionalWebsiteMattersMoratoriaImport } from './routes/resources/why-professional-website-matters'
import { Route as ResourcesDigitalPresenceChecklistImport } from './routes/resources/digital-presence-checklist'
import { Route as ResourcesMarketingEssentialsImport } from './routes/resources/marketing-essentials'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as MeetOurTeamRouteImport } from './routes/meet-our-team'
import { Route as LaunchProgramRouteImport } from './routes/launch-program'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetOurTeamRoute = MeetOurTeamRouteImport.update({
  id: '/meet-our-team',
  path: '/meet-our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchProgramRoute = LaunchProgramRouteImport.update({
  id: '/launch-program',
  path: '/launch-program',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/launch-program': typeof LaunchProgramRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/launch-program': typeof LaunchProgramRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/launch-program': typeof LaunchProgramRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/launch-program'
    | '/meet-our-team'
    | '/process'
    | '/resources'
    | '/results'
    | '/services'
    | '/why-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/launch-program'
    | '/meet-our-team'
    | '/process'
    | '/resources'
    | '/results'
    | '/services'
    | '/why-us'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/launch-program'
    | '/meet-our-team'
    | '/process'
    | '/resources'
    | '/results'
    | '/services'
    | '/why-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LaunchProgramRoute: typeof LaunchProgramRoute
  MeetOurTeamRoute: typeof MeetOurTeamRoute
  ProcessRoute: typeof ProcessRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  ServicesRoute: typeof ServicesRoute
  WhyUsRoute: typeof WhyUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-our-team': {
      id: '/meet-our-team'
      path: '/meet-our-team'
      fullPath: '/meet-our-team'
      preLoaderRoute: typeof MeetOurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-program': {
      id: '/launch-program'
      path: '/launch-program'
      fullPath: '/launch-program'
      preLoaderRoute: typeof LaunchProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LaunchProgramRoute: LaunchProgramRoute,
  MeetOurTeamRoute: MeetOurTeamRoute,
  ProcessRoute: ProcessRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  ServicesRoute: ServicesRoute,
  WhyUsRoute: WhyUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
